{"original_code": "def test_unhandled_exception(ep, json_request, assert_log_errors):\n    resp = json_request(\n        {\n            \"id\": 111,\n            \"jsonrpc\": \"2.0\",\n            \"method\": \"unhandled_exception\",\n            \"params\": {},\n        }\n    )\n\n    assert resp == {\n        \"jsonrpc\": \"2.0\",\n        \"id\": 111,\n        \"error\": {\n            \"code\": -32603,\n            \"message\": \"Internal error\",\n        },\n    }\n\n    assert_log_errors(\"My unhandled exception\", pytest.raises(MyUnhandledException))"}