{"original_code": "    async def mw_exception_exit(ctx: jsonrpc.JsonRpcContext):\n        nonlocal _calls\n        _calls[ctx.raw_request.get(\"id\")].append(\n            (\n                \"mw_exception_exit\",\n                \"enter\",\n                ctx.raw_request,\n                ctx.raw_response,\n                sys.exc_info()[0],\n            )\n        )\n        # noinspection PyUnreachableCode\n        try:\n            yield\n        finally:\n            _calls[ctx.raw_response.get(\"id\")].append(\n                (\n                    \"mw_exception_exit\",\n                    \"exit\",\n                    ctx.raw_request,\n                    ctx.raw_response,\n                    sys.exc_info()[0],\n                )\n            )\n            raise RuntimeError(unique_marker)"}