    async def handle_exception(self, exc) -> dict:
        raise exc